import type { PricingCatalog } from "../types.js";

/**
 * Seed pricing catalog. Prices are in USD per 1M tokens.
 *
 * IMPORTANT: Provider pricing changes frequently. This is a working default so
 * the CLI produces useful estimates out of the box. Users should review and
 * update `.agentspend/pricing.models.json` before making financial decisions.
 */
export const SEED_PRICING: PricingCatalog = {
  version: 1,
  currency: "USD",
  unit: "per_1m_tokens",
  notes:
    "Default seed catalog. Review and update before making financial decisions. Prices subject to change.",
  models: [
    // ------- OpenAI -------
    {
      provider: "openai",
      model: "gpt-4o",
      input_per_1m: 2.5,
      output_per_1m: 10.0,
      cached_input_per_1m: 1.25,
      batch_input_multiplier: 0.5,
      batch_output_multiplier: 0.5,
      capabilities: ["chat", "tool_calling", "structured_output", "vision"],
      quality_tier: "frontier",
    },
    {
      provider: "openai",
      model: "gpt-4o-mini",
      input_per_1m: 0.15,
      output_per_1m: 0.6,
      cached_input_per_1m: 0.075,
      batch_input_multiplier: 0.5,
      batch_output_multiplier: 0.5,
      capabilities: ["chat", "tool_calling", "structured_output"],
      quality_tier: "cheap",
    },
    {
      provider: "openai",
      model: "gpt-4.1",
      input_per_1m: 2.0,
      output_per_1m: 8.0,
      cached_input_per_1m: 0.5,
      batch_input_multiplier: 0.5,
      batch_output_multiplier: 0.5,
      capabilities: ["chat", "tool_calling", "structured_output"],
      quality_tier: "frontier",
    },
    {
      provider: "openai",
      model: "gpt-4.1-mini",
      input_per_1m: 0.4,
      output_per_1m: 1.6,
      cached_input_per_1m: 0.1,
      batch_input_multiplier: 0.5,
      batch_output_multiplier: 0.5,
      capabilities: ["chat", "tool_calling", "structured_output"],
      quality_tier: "mid",
    },
    {
      provider: "openai",
      model: "gpt-4.1-nano",
      input_per_1m: 0.1,
      output_per_1m: 0.4,
      cached_input_per_1m: 0.025,
      batch_input_multiplier: 0.5,
      batch_output_multiplier: 0.5,
      capabilities: ["chat", "structured_output"],
      quality_tier: "cheap",
    },
    {
      provider: "openai",
      model: "gpt-4-turbo",
      input_per_1m: 10.0,
      output_per_1m: 30.0,
      batch_input_multiplier: 0.5,
      batch_output_multiplier: 0.5,
      capabilities: ["chat", "tool_calling"],
      quality_tier: "premium",
      aliases: ["gpt-4-turbo-preview", "gpt-4-0125-preview"],
    },
    {
      provider: "openai",
      model: "gpt-4",
      input_per_1m: 30.0,
      output_per_1m: 60.0,
      capabilities: ["chat"],
      quality_tier: "premium",
    },
    {
      provider: "openai",
      model: "gpt-3.5-turbo",
      input_per_1m: 0.5,
      output_per_1m: 1.5,
      capabilities: ["chat"],
      quality_tier: "cheap",
    },
    {
      provider: "openai",
      model: "o1",
      input_per_1m: 15.0,
      output_per_1m: 60.0,
      cached_input_per_1m: 7.5,
      capabilities: ["reasoning", "chat"],
      quality_tier: "frontier",
    },
    {
      provider: "openai",
      model: "o1-mini",
      input_per_1m: 3.0,
      output_per_1m: 12.0,
      cached_input_per_1m: 1.5,
      capabilities: ["reasoning", "chat"],
      quality_tier: "mid",
    },
    {
      provider: "openai",
      model: "o3-mini",
      input_per_1m: 1.1,
      output_per_1m: 4.4,
      cached_input_per_1m: 0.55,
      capabilities: ["reasoning", "chat"],
      quality_tier: "mid",
    },
    {
      provider: "openai",
      model: "text-embedding-3-small",
      input_per_1m: 0.02,
      output_per_1m: 0,
      capabilities: ["embedding"],
      quality_tier: "cheap",
    },
    {
      provider: "openai",
      model: "text-embedding-3-large",
      input_per_1m: 0.13,
      output_per_1m: 0,
      capabilities: ["embedding"],
      quality_tier: "mid",
    },
    {
      provider: "openai",
      model: "text-embedding-ada-002",
      input_per_1m: 0.1,
      output_per_1m: 0,
      capabilities: ["embedding"],
      quality_tier: "cheap",
    },

    // ------- Anthropic -------
    {
      provider: "anthropic",
      model: "claude-opus-4",
      input_per_1m: 15.0,
      output_per_1m: 75.0,
      cached_input_per_1m: 1.5,
      batch_input_multiplier: 0.5,
      batch_output_multiplier: 0.5,
      capabilities: ["chat", "tool_calling", "coding", "reasoning"],
      quality_tier: "frontier",
      aliases: ["claude-opus-4-0", "claude-opus-4-20250514"],
    },
    {
      provider: "anthropic",
      model: "claude-sonnet-4.5",
      input_per_1m: 3.0,
      output_per_1m: 15.0,
      cached_input_per_1m: 0.3,
      batch_input_multiplier: 0.5,
      batch_output_multiplier: 0.5,
      capabilities: ["chat", "tool_calling", "coding", "structured_output"],
      quality_tier: "frontier",
      aliases: ["claude-sonnet-4-5", "claude-sonnet-4.5-20250101"],
    },
    {
      provider: "anthropic",
      model: "claude-sonnet-4",
      input_per_1m: 3.0,
      output_per_1m: 15.0,
      cached_input_per_1m: 0.3,
      batch_input_multiplier: 0.5,
      batch_output_multiplier: 0.5,
      capabilities: ["chat", "tool_calling", "coding"],
      quality_tier: "frontier",
      aliases: ["claude-sonnet-4-0"],
    },
    {
      provider: "anthropic",
      model: "claude-3-5-sonnet",
      input_per_1m: 3.0,
      output_per_1m: 15.0,
      cached_input_per_1m: 0.3,
      batch_input_multiplier: 0.5,
      batch_output_multiplier: 0.5,
      capabilities: ["chat", "tool_calling", "coding"],
      quality_tier: "frontier",
      aliases: [
        "claude-3-5-sonnet-latest",
        "claude-3-5-sonnet-20241022",
        "claude-3.5-sonnet",
        "claude-sonnet",
      ],
    },
    {
      provider: "anthropic",
      model: "claude-3-5-haiku",
      input_per_1m: 0.8,
      output_per_1m: 4.0,
      cached_input_per_1m: 0.08,
      batch_input_multiplier: 0.5,
      batch_output_multiplier: 0.5,
      capabilities: ["chat", "tool_calling", "structured_output"],
      quality_tier: "cheap",
      aliases: ["claude-haiku", "claude-3.5-haiku", "claude-3-5-haiku-latest"],
    },
    {
      provider: "anthropic",
      model: "claude-3-opus",
      input_per_1m: 15.0,
      output_per_1m: 75.0,
      capabilities: ["chat", "tool_calling"],
      quality_tier: "premium",
      aliases: ["claude-3-opus-latest", "claude-opus"],
    },
    {
      provider: "anthropic",
      model: "claude-3-haiku",
      input_per_1m: 0.25,
      output_per_1m: 1.25,
      capabilities: ["chat"],
      quality_tier: "cheap",
    },

    // ------- Google Gemini -------
    {
      provider: "gemini",
      model: "gemini-2.0-flash",
      input_per_1m: 0.1,
      output_per_1m: 0.4,
      capabilities: ["chat", "tool_calling", "structured_output"],
      quality_tier: "cheap",
    },
    {
      provider: "gemini",
      model: "gemini-1.5-pro",
      input_per_1m: 1.25,
      output_per_1m: 5.0,
      capabilities: ["chat", "tool_calling"],
      quality_tier: "frontier",
    },
    {
      provider: "gemini",
      model: "gemini-1.5-flash",
      input_per_1m: 0.075,
      output_per_1m: 0.3,
      capabilities: ["chat"],
      quality_tier: "cheap",
    },

    // ------- Local / OSS placeholder -------
    {
      provider: "local",
      model: "local-oss-model-placeholder",
      input_per_1m: 0,
      output_per_1m: 0,
      cached_input_per_1m: 0,
      batch_input_multiplier: 1,
      batch_output_multiplier: 1,
      capabilities: ["chat", "summarization", "classification", "extraction"],
      quality_tier: "oss",
    },
  ],
};
